# Generated by Django 5.0.3 on 2024-11-15 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadtest', '0004_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='loadtest.loadtest'),
            preserve_default=False,
        ),
    ]
